<a href="https://colab.research.google.com/github/IUBAYAR/MIS-351/blob/main/Simulating_Gamma%26Weibull.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#  install basic python modules
!pip install numpy
!pip install pandas
!pip install matplotlib
!pip install seaborn

  Using cached numpy-2.0.2-cp39-cp39-macosx_14_0_arm64.whl.metadata (60 kB)
Using cached numpy-2.0.2-cp39-cp39-macosx_14_0_arm64.whl (5.3 MB)
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
statsmodels 0.14.4 requires pandas!=2.1.0,>=1.4, which is not installed.
  Using cached pandas-2.2.3-cp39-cp39-macosx_11_0_arm64.whl.metadata (89 kB)
Using cached pandas-2.2.3-cp39-cp39-macosx_11_0_arm64.whl (11.3 MB)
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
ppscore 1.3.0 requires pandas<2.0.0,>=1.0.0, but you have pandas 2.2.3 which is incompatible.
  Using cached matplotlib-3.9.4-cp39-cp39-macosx_11_0_arm64.whl.metadata (11 kB)
Using cached matplotlib-3.9.4-cp39-cp39-macosx_11_0_arm64.whl (7.8 MB)
  Using cached seaborn-0.13.2-py3-none-any.w

In [ ]:
#  start python modules running
import numpy as np
import pandas as pd

#  Gamma Distribution

np.random.gamma() has 3 arguments:
* shape (k),
* scale (expected time intervals between events),
* size

shape and scale defines the number of occurances of a specific event, and the usual (expected) time lapse between occurances of that event.
size is the number random numbers generated.

A gamma distribution is an extension to the Poisson or Exponential distributions.
In a Poisson dist. the random variable is the number of occurances of a specific event within a time period,
in an Exponential dist. the random variable is the time you need to wait until the event occurs for the first time.
On the other hand, for the Gamma distribution, the random variable is the time you need to wait until k events occur.

## Problem

So, we did not schedule the class on a specific time. But we had said that it will be in wednesday afternoon.

I have arrived to the school and I am waiting for the students to appear.

The class enrollment is 20 students, and I need at least 60% in class. How long do I have to wait?

I have monitored that each 217 seconds a student comes to the class.

In [ ]:
k = 12
scale = 217

In [ ]:
#  create a large number of random variable instances
np.random.gamma(
                shape = k,
                scale = scale,
                size = 10**6
                )

array([1983.35347757, 3408.81002614, 3392.62637741, ..., 2688.81870824,
       1953.77222837, 2455.21875917])

In [ ]:
#  Computing the expected time before 12 students appear in class
X = np.random.gamma(
                shape = k,
                scale = scale,
                size = 10**6
                )

X.mean() / 60

np.float64(43.39609072838296)

What is the probability that I get to wait for no longer than 20 minutes?

In [ ]:
20 * 60

1200

In [ ]:
#  I need to filter down the instances with values no larger than 300
#    First I transform my numpy.array object to a pandas.Series object
X = pd.Series( X )

X

0         2192.857920
1         2804.197280
2         2083.902547
3         2053.554350
4         3570.478432
             ...     
999995    2103.775181
999996    2871.657017
999997    2465.568693
999998    1409.485988
999999    1982.756627
Length: 1000000, dtype: float64

In [ ]:
#    I filter down the instances with values no larger than 1200
X[ X <= 1200 ]

65        1123.791871
189       1059.201334
334       1142.964024
350       1108.347257
505       1154.622797
             ...     
999596    1042.647210
999763    1166.054519
999803    1166.119742
999811    1178.280175
999817    1198.204343
Length: 11383, dtype: float64

In [ ]:
#    Now I compute the probability
( len(X[ X <= 1200 ]) ) / ( len(X) )

0.011383

#  Weibull Distibution

np.random.weibull() has two arguments:
* a
* size

a is non-negative number that indicates how time affects the likelihood of failure.
- if a < 1, then as time passes, its less and less likely to see failure
- if a = 1, then the failure is time-invariant
- if a > 1, then as time passes, its more and more likely to see failure

size is the number of random numbers you generate

A weibull is distribution is the number of units that break down in a given time period. Weibull distribution is generally used for reliability problems.

## Weibull problem

I have 10ooo light bulbs in the congressium center. What is the time required to see all those bulbs changed?

The lights are more likely to fail as time passes. Take a as 1.15.

It is expected see a light bulb to last 1000 hours.

In [ ]:
np.random.weibull(
a = 1.15,
size = 10
)

array([0.23494096, 3.02801063, 1.50499237, 0.86441675, 0.4364179 ,
       0.2978756 , 0.36579709, 1.35142625, 0.03812407, 0.57926435])

np.random.weibull() gives you time coefficient for life time of your system

In [ ]:
#  Lets create a random variable with large number of instances
X = 1000 * np.random.weibull(
                            a = 1.15,
                            size = (10000, 10**3)
                            )

X

array([[ 143.32156634,  270.83231307, 1042.88385171, ...,  322.36902444,
         301.20500165,  492.47670664],
       [2216.33132003,  398.77474989,  333.91133639, ..., 2191.74851794,
         522.25972513, 1627.24339238],
       [ 424.6156314 ,  242.4926454 , 1040.49665116, ..., 1543.73313725,
        1274.13733739, 1655.54056331],
       ...,
       [ 549.98046194,   49.30210498, 1232.3222022 , ..., 1476.58246565,
        1134.38456987, 1105.97895849],
       [ 723.29492933,  705.89291681, 1603.79349919, ..., 1319.58990035,
         410.64303026, 2446.19090219],
       [ 672.17059917,  875.8536439 , 1532.32295901, ..., 1172.55934334,
        2134.39016245, 1183.06327879]])

In [ ]:
#  Lets see the mean values
#    Transform X into a pandas Series
X = pd.DataFrame( X.T )
X

0            1            2            3            4     \
0     143.321566  2216.331320   424.615631   286.225520   993.562070   
1     270.832313   398.774750   242.492645   156.911261  1153.693634   
2    1042.883852   333.911336  1040.496651   185.475592   487.961137   
3     688.333053   718.086049   633.399743   952.732490  2281.153598   
4     114.493845   233.128144  2301.805651    93.884531    32.004084   
..           ...          ...          ...          ...          ...   
995  1375.510321  1555.539748   929.321820  1038.824774   927.713439   
996   876.604606  1106.555940   202.196057   298.644995   843.800589   
997   322.369024  2191.748518  1543.733137    99.539197    93.089196   
998   301.205002   522.259725  1274.137337   371.241386  1725.001112   
999   492.476707  1627.243392  1655.540563   399.660144  1080.259486   

            5            6            7            8            9     ...  \
0     144.975646   218.241463   776.782007    60.958548  1242.835457  ...   
1    3049.128343   602.034188  1742.458807   215.924394   334.919500  ...   
2     962.084995   112.568252   133.108975  1362.290354  1209.404355  ...   
3    1727.394895   533.482549  1784.535747   172.998284  1077.885300  ...   
4    1582.357284  1572.478472  2674.894934  3173.124806    78.408263  ...   
..           ...          ...          ...          ...          ...  ...   
995   264.485137   798.819164  2745.896040  3251.437152  1685.429674  ...   
996   704.925927   841.001302   743.056592  1000.671667  1182.160382  ...   
997   120.861058   281.732275   529.350674   966.827970   225.852977  ...   
998   366.045701   339.354877  1545.612144  1530.964789   364.140432  ...   
999  2280.045994   649.169568   155.556030   211.474920    78.625879  ...   

            9990         9991         9992         9993         9994  \
0    1106.942890   645.820730  1093.465012  2464.536326  1105.886588   
1    1215.147800  1045.422287  2286.044436   338.323097   472.202348   
2    2071.032905  2094.267174   561.922469  2045.342113  1011.484814   
3     255.658917   435.951085   676.792476   898.284115   488.504556   
4     233.211960  1842.579648   453.319078  1170.323471  2343.616013   
..           ...          ...          ...          ...          ...   
995  2736.310945  2812.987020  2339.303532  1970.947934  1530.186509   
996   165.625403  1035.639825   841.931499   794.227065   104.371734   
997    94.328904   925.462311   326.401177    67.197257   780.095818   
998   605.543736   521.943429   830.773072    77.144663  1851.949822   
999   581.352264   307.322983  1245.339463   361.340069  1299.041784   

            9995         9996         9997         9998         9999  
0    1068.074056  2849.528964   549.980462   723.294929   672.170599  
1    1134.125630  1367.993062    49.302105   705.892917   875.853644  
2      59.367559  1689.122532  1232.322202  1603.793499  1532.322959  
3    3245.587020  2940.337126  1678.207490   476.419737   707.282789  
4     447.729826  1528.931166   571.340778  1866.667277   767.300043  
..           ...          ...          ...          ...          ...  
995    44.553841  1558.248872   294.127276   616.512653  1092.467376  
996   138.044389  2957.311587   537.054237  1381.834931   160.765304  
997   260.074245   250.777048  1476.582466  1319.589900  1172.559343  
998  1159.030947  1805.809020  1134.384570   410.643030  2134.390162  
999  2104.041331  1139.006278  1105.978958  2446.190902  1183.063279  

[1000 rows x 10000 columns]

Before transposing X (pd.DataFrame( X )) we had a table for which the rows represented for each light bulb (one of 10000), and columns represented for each random instance out of 1000.

For this version X.mean() computed the mean value for each random instance rather than for each lightbulb.

This is why we transposed (rotated) our data ( pd.DataFrame( X.T ) ).
                                                                                                                                               

In [ ]:
X.mean()

0       1003.615351
1        940.142952
2        913.741757
3        993.950953
4        951.255936
           ...     
9995     945.967979
9996     928.146645
9997    1002.787886
9998     957.330607
9999     951.458895
Length: 10000, dtype: float64

For this list of expected lifetime of bulbs, we are asked for the time to change all the lightbulbs. So, now we need the max value here.

The max of means, will give us the very last one of the original 10ooo lightbulbs that is finally broken.

In [ ]:
X.mean().max()

np.float64(1041.9156295937087)

So, when do I need to change the first lightbulb? What is the probability that changing all the bulbs after 900 hours would be okay?

In [ ]:
X.mean().min()

np.float64(866.1852886062591)

In [ ]:
X.mean() [ X.mean() > 900 ]

0       1003.615351
1        940.142952
2        913.741757
3        993.950953
4        951.255936
           ...     
9995     945.967979
9996     928.146645
9997    1002.787886
9998     957.330607
9999     951.458895
Length: 9777, dtype: float64

In [ ]:
len( X.mean()[ X.mean() > 900 ] ) / len( X.mean() )

0.9777

Hint: do not immediately use the mean values.

For the Weibull distributed lightbulbs question. What is the probability that no lights go out in 800 hours?